# Generated by Django 5.2.1 on 2025-07-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_watered', models.DateTimeField(auto_now=True)),
                ('api_plant_id', models.CharField(blank=True, max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True)),
                ('observation', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='plant_pics')),
                ('log_date', models.DateTimeField(auto_now=True)),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('disease_detected', models.CharField(blank=True, max_length=200)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='tracker.userplant')),
            ],
        ),
    ]
