# Generated by Django 5.2.1 on 2025-08-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='plant_thumbnail'),
        ),
    ]
