# Generated by Django 5.2.1 on 2025-08-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userplant_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='planthealth',
            name='disease_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_treatment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userplant',
            name='care_light',
            field=models.TextField(blank=True, help_text='Light requirements from API'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='care_soil',
            field=models.TextField(blank=True, help_text='Soil preferences from API'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='care_watering',
            field=models.TextField(blank=True, help_text='Watering instructions from API'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='plant_description',
            field=models.TextField(blank=True, help_text='General description from API'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='toxicity_info',
            field=models.TextField(blank=True, help_text='Toxicity information from API'),
        ),
        migrations.AlterField(
            model_name='planthealth',
            name='plant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='tracker.userplant', verbose_name='Plant name'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='plant_thumbnail', verbose_name='Image'),
        ),
    ]
