# Generated by Django 5.2.1 on 2025-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_planthealth_disease_cause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planthealth',
            name='disease_treatment',
        ),
        migrations.RemoveField(
            model_name='planthealth',
            name='health_score',
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_treatment_biological',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_treatment_chemical',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_treatment_prevention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planthealth',
            name='disease_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planthealth',
            name='disease_detected',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='planthealth',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='plant_pics'),
        ),
    ]
