# Generated by Django 5.2.1 on 2025-11-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_planthealth_disease_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planthealth',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
