# Generated by Django 5.2.1 on 2025-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_planthealth_checked_alter_userplant_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planthealth',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
